version: "3"
services:
  worker:
    image: gcr.io/restaurant-order-192310/ro-order-worker:latest
    ports:
      - 9000:9000
    volumes:
      - realm-data:/usr/src/app/DataRealm

  api:
    image: gcr.io/restaurant-order-192310/ro-order-api:latest
    ports:
      - 3000:3000
    volumes:
      - realm-data:/usr/src/app/DataRealm

volumes:
  realm-data: