version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - ro

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - '9100:9100'
    networks:
      - ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "9191:3000"
    networks:
      - ro

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-basic:6.2.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - ./elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticdata:/usr/share/elasticsearch/data
    networks:
      - ro
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - 'ELASTIC_PASSWORD=DBSxcN6U'

  logstash:
    image: docker.elastic.co/logstash/logstash-x-pack:6.2.3
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./elk/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - ro
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    depends_on:
      - elasticsearch

  filebeat:
    # image: docker.elastic.co/beats/filebeat:6.2.2
    build:
      context: ./elk
    container_name: filebeat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
      - ./elk/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    networks:
      - ro
    depends_on:
      - logstash

  kibana:
    image: docker.elastic.co/kibana/kibana-x-pack:6.2.3
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./elk/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - ro
    depends_on:
      - elasticsearch

volumes:
  prometheus_data: {}
  grafana_data: {}
  elasticdata: {}

networks:
  ro:
    driver: bridge