version: '3'
services:

  order-worker:
    image: gcr.io/restaurant-order-192310/ro-order-worker:dev
    container_name: order-worker
    ports:
      - 9200:9000
    volumes:
      - realm-data:/usr/src/app/DataRealm
    networks:
      - rodevops_ro
    environment:
    - DEV

  order-api:
    image: gcr.io/restaurant-order-192310/ro-order-api:dev
    container_name: order-api
    ports:
      - 3200:3000
    volumes:
      - realm-data:/usr/src/app/DataRealm
    networks:
      - rodevops_ro
    environment:
    - DEV

  admin-api:
    image: gcr.io/restaurant-order-192310/ro-admin-api:dev
    container_name: admin-api
    ports:
      - 4200:4000
    volumes:
      - realm-data:/usr/src/app/DataRealm
    networks:
      - rodevops_ro
    environment:
    - DEV

  order-app:
    image: gcr.io/restaurant-order-192310/ro-order-app:dev
    container_name: order-app
    ports:
      - 82:80
    networks:
      - rodevops_ro
    environment:
    - DEV

volumes:
  realm-data:

networks:
  rodevops_ro:
    external: true 
