version: '3'
services:

  order-worker:
    image: gcr.io/restaurant-order-192310/ro-order-worker:dev
    container_name: order-worker-dev
    ports:
      - 9200:9000
    volumes:
      - realm-data:/usr/src/app/DataRealm
    networks:
      - rodevops_ro
    environment:
      - DEV=1

  order-api:
    image: gcr.io/restaurant-order-192310/ro-order-api:dev
    container_name: order-api-dev
    ports:
      - 3200:3000
    volumes:
      - realm-data:/usr/src/app/DataRealm
    networks:
      - rodevops_ro
    environment:
      - DEV=1

  admin-api:
    image: gcr.io/restaurant-order-192310/ro-admin-api:dev
    container_name: admin-api-dev
    ports:
      - 4200:4000
    volumes:
      - realm-data:/usr/src/app/DataRealm
    networks:
      - rodevops_ro
    environment:
      - DEV=1

  order-app:
    image: gcr.io/restaurant-order-192310/ro-order-app:dev
    container_name: order-app-dev
    ports:
      - 82:80
    networks:
      - rodevops_ro

  admin-app:
    image: gcr.io/restaurant-order-192310/ro-admin-app:dev
    container_name: admin-app-dev
    ports:
      - 92:80
    networks:
      - rodevops_ro
  
  analyze-api:
    image: gcr.io/restaurant-order-192310/ro-analyze-api:dev
    container_name: analyze-api-dev
    ports:
      - 5200:80
    networks:
      - rodevops_ro
    environment:
      - DEV=1

  auth-api:
    image: gcr.io/restaurant-order-192310/ro-auth-api:dev
    container_name: auth-api-dev
    volumes:
      - auth-data:/usr/src/app/DataRealm
    networks:
      - rodevops_ro
    ports:
      - 2200:4000

  webpage:
    image: gcr.io/restaurant-order-192310/ro-webpage:dev
    container_name: webpage-dev
    networks:
      - rodevops_ro
    ports:
      - 10000:80

volumes:
  realm-data:
  auth-data:

networks:
  rodevops_ro:
    external: true