version: '3'
services:

  order-worker:
    image: gcr.io/restaurant-order-192310/ro-order-worker:dev
    container_name: order-worker-dev
    ports:
      - 9200:9000
    volumes:
      - realm-data:/usr/src/app/DataRealm
    networks:
      - rodevops_ro
    environment:
      - DEV

  order-api:
    image: gcr.io/restaurant-order-192310/ro-order-api:dev
    container_name: order-api-dev
    ports:
      - 3200:3000
    volumes:
      - realm-data:/usr/src/app/DataRealm
    networks:
      - rodevops_ro
    environment:
      - DEV

  admin-api:
    image: gcr.io/restaurant-order-192310/ro-admin-api:dev
    container_name: admin-api-dev
    ports:
      - 4200:4000
    volumes:
      - realm-data:/usr/src/app/DataRealm
    networks:
      - rodevops_ro
    environment:
      - DEV

  order-app:
    image: gcr.io/restaurant-order-192310/ro-order-app:dev
    container_name: order-app-dev
    ports:
      - 82:80
    networks:
      - rodevops_ro
    environment:
      - DEV
  
  analyze-api:
    image: gcr.io/restaurant-order-192310/ro-analyze-api:dev
    container_name: analyze-api-dev
    ports:
      - 5200:80
    networks:
      - rodevops_ro
    environment:
      - DEV

volumes:
  realm-data:

networks:
  rodevops_ro:
    external: true