version: '3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    volumes:
      - ./config:/data
    environment:
      - SWAGGER_JSON=/data/order.json
      - SWAGGER_JSON=/data/admin.json
    ports:
      - '1000:8080'