version: '3'
services:
  swagger-ui-admin:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui-admin
    volumes:
      - ./config:/data
    environment:
      - SWAGGER_JSON=/data/admin.json
    ports:
      - '4080:8080'
  swagger-ui-order:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui-order
    volumes:
      - ./config:/data
    environment:
      - SWAGGER_JSON=/data/order.json
    ports:
      - '3080:8080'