global:
  scrape_interval: 15s 
  evaluation_interval: 15s
  scrape_timeout: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cAdvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'order-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['order-api:3000']
  - job_name: 'admin-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['admin-api:4000']