version: "3"
services:
  order-worker:
    image: gcr.io/restaurant-order-192310/ro-order-worker:latest
    container_name: order-worker
    ports:
      - 9000:9000
    volumes:
      - realm-data:/usr/src/app/DataRealm

  order-api:
    image: gcr.io/restaurant-order-192310/ro-order-api:latest
    container_name: order-api
    ports:
      - 3000:3000
    volumes:
      - realm-data:/usr/src/app/DataRealm

  admin-api:
    image: gcr.io/restaurant-order-192310/ro-admin-api
    container_name: admin-api
    ports:
      - 4000:4000
    volumes:
      - realm-data:/usr/src/app/DataRealm


volumes:
  realm-data: