version: '3'
services:

  order-worker:
    image: gcr.io/restaurant-order-192310/ro-order-worker:master
    container_name: order-worker-prod
    ports:
      - 9000:9000
    volumes:
      - realm-data:/usr/src/app/DataRealm
    networks:
      - rodevops_ro
    environment:
      - PROD=1

  order-api:
    image: gcr.io/restaurant-order-192310/ro-order-api:master
    container_name: order-api-prod
    ports:
      - 3000:3000
    volumes:
      - realm-data:/usr/src/app/DataRealm
    networks:
      - rodevops_ro
    environment:
      - PROD=1

  admin-api:
    image: gcr.io/restaurant-order-192310/ro-admin-api:master
    container_name: admin-api-prod
    ports:
      - 4000:4000
    volumes:
      - realm-data:/usr/src/app/DataRealm
    networks:
      - rodevops_ro
    environment:
      - PROD=1

  order-app:
    image: gcr.io/restaurant-order-192310/ro-order-app:master
    container_name: order-app-prod
    ports:
      - 80:80
    networks:
      - rodevops_ro
    environment:
      - PROD=1

  analyze-api:
    image: gcr.io/restaurant-order-192310/ro-analyze-api:master
    container_name: analyze-api-prod
    ports:
      - 5000:80
    environment:
      - PROD=1
  
  auth-api:
    image: gcr.io/restaurant-order-192310/ro-auth-api:master
    container_name: auth-api-prod
    volumes:
      - realm-data:/usr/src/app/DataRealm
    networks:
      - rodevops_ro
    ports:
      - 2000:4000
    environment:
      - PROD=1

volumes:
  realm-data:

networks:
  rodevops_ro:
    external: true 
